services:
  web:
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/sweb/nginx/Dockerfile
      #autor: ${AUTOR}
      # args: #variables en DFILE para la construccion (build) de la imagen
        # - USUARIO=alfonso
    image: dsegura97/nginx 
    container_name: ${CONTENEDOR}
    #hostame: ${HOSTNAME}
    # environment: # si necesito algun v.e que no est√© en la .env
    #   - USUARIO=alfonso
    #   - PASSWORD=pswalfonso
    env_file:
      - ./.env
    ports:
      - "${PORT_WEB}:80"
    volumes:
      - ./logs:/root/logs
    networks:
      netcarontewebnginx:
        ipv4_address: ${IP_WEB}
  networks:
      netcarontewebnginx:
        driver: bridge
        ipam:
          driver: default
          config:
          - subnet: ${SUBNET}