services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/nodejs/node
    container_name: ${CONTENEDOR}
    ports:
      - "3000:80"    
    env_file:
      - ./.env
    image: dsegura97/nodejs
    volumes:
      - ./logs:/root/logs      
    networks:
      netnode:
        ipv4_address: ${IP}
networks:
  netnode:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}