services:

  web:
    build:
      context: /home/david/devops/Docker/Caronte/dockerfiles/proyectos/pbase/deploy
      dockerfile: ./dockerfiles/base/ubbase
      args:
        - USUARIO=pepe 
    container_name: ctbase_ubbase