services:
  web:
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/base/david
      autor: ${AUTOR}
      # args: #variables en DFILE para la construccion (build) de la imagen
        # - USUARIO=alfonso
    container_name: ${CONTENEDOR}
    # environment: # si necesito algun v.e que no est√© en la .env
    #   - USUARIO=alfonso
    #   - PASSWORD=pswalfonso
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      netcaronte:
        ipv4_address: ${IP_WEB}
networks:
  netcaronte:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}