services:

  web:
    build:
      context: ${CONTEXTO} 
      dockerfile: ./dockerfiles/base/ubbase
      #args:
        # - USUARIO=alfonso 
    container_name: ${CONTENEDOR}

    ENV_FILE:
      - ./.env
    volumes:
      - ./logs:/root/logs