services:
  servidor:
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/proyecto-iaw/iaw
      args:
        - AUTOR=${AUTOR}
    image: dsegura97/node
    container_name: ${CONTENEDOR}
    hostname: ${HOSTNAME}
    
    env_file:
      - ./.env
    ports:
      - 8100:80
      - 30002:3000
    volumes:
      - ./logs:/root/logs
    networks:
      netcarontewebnginx:
        ipv4_address: ${IP}

networks:
   netcarontewebnginx:
     ipam:
       driver: default
       config:
         - subnet: ${SUBNET}