services:
  servidor:
    build: 
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/sweb/nginx/nginxbase
      args:
        - AUTOR=${AUTOR}
    image: dsegura97/nginx 
    container_name: ${CONTENEDOR}
    hostname: ${HOSTNAME}
    
    env_file:
      - ./.env
    ports:
      - ${PORT_WEB}:22
    volumes:
      - ./logs:/root/logs
    networks:
      netcarontewebnginx:
        ipv4_address: ${IP}

networks:
   netcarontewebnginx:
     ipam:
       driver: default
       config:
         - subnet: ${SUBNET}